import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';
import { RENOVA_CONFIG, isSupabaseConfigured } from './config.js?v=20260914-001';
import { loadDashboard } from './dashboard-module.js?v=20260913-002';
import { createPublicStore } from './public-store.js?v=20260914-002';
import { createInternalModules } from './internal-modules.js?v=20260914-001';
import { createExtrasModules } from './extras-modules.js?v=20260914-001';
import { createAdminPlanModule } from './admin-plan-module.js?v=20260914-001';
import { createNetworkingMediaModule } from './networking-media-module.js?v=20260914-001';
import { createProductManagement } from './product-management.js?v=20260914-002';
import { createAgendaModule } from './agenda-module.js?v=20260914-001';
import { createPublicBooking } from './public-booking.js?v=20260914-001';
import { createDeveloperPage } from './developer-page.js?v=20260914-001';

const $=(selector,root=document)=>root.querySelector(selector);
const $$=(selector,root=document)=>[...root.querySelectorAll(selector)];
const root=document.documentElement,body=document.body;
let supabase=null,currentUser=null,currentProfile=null,currentCompany=null,publicStore=null,internalModules=null,extrasModules=null,adminPlanModule=null,networkingMediaModule=null,productManagement=null,agendaModule=null,publicBooking=null,developerPage=null,publicCatalogLoaded=false,canAgenda=false;

const pageMeta={dashboard:['VISÃO GERAL','Painel'],crm:['GESTÃO','CRM / Clientes'],sales:['GESTÃO','Vendas'],orders:['OPERAÇÃO','Ordens de Serviço'],tasks:['PRODUTIVIDADE','Tarefas / Agenda'],products:['CATÁLOGO','Produtos / Serviços'],appointments:['CONSULTORIAS','Agendamentos'],finance:['FINANCEIRO','Financeiro'],ai:['INTELIGÊNCIA','RENOVA IA'],affiliates:['CRESCIMENTO','Afiliados'],members:['CONHECIMENTO','Área de Membros'],developer:['INSTITUCIONAL','Desenvolvedor'],settings:['SISTEMA','Configurações'],admin:['ADMINISTRAÇÃO','Administração']};
const low=v=>String(v??'').trim().toLowerCase();

function showToast(message,timeout=3000){const toast=$('#toast');if(!toast)return;toast.textContent=message;toast.classList.add('show');clearTimeout(showToast._timer);showToast._timer=setTimeout(()=>toast.classList.remove('show'),timeout)}
function applyBrand(){const {brand}=RENOVA_CONFIG;['#authLogo','#authLogoMobile','#sidebarLogo','#companyLogo'].forEach(id=>{const img=$(id);if(img)img.src=brand.logoUrl});const dev=$('#developerPhoto');if(dev)dev.src=brand.developerPhotoUrl}
function preferredTheme(){return localStorage.getItem('renova_web_theme')==='dark'?'dark':'light'}
function applyTheme(theme){root.dataset.theme=theme;localStorage.setItem('renova_web_theme',theme);const meta=$('meta[name="theme-color"]');if(meta)meta.content=theme==='dark'?'#061426':'#f6f9fc';const btn=$('#themeToggle');if(btn)btn.textContent=theme==='dark'?'☀':'☾';publicStore?.syncThemeIcon?.()}
function closeMobileMenu(){body.classList.remove('menu-open');const btn=$('#mobileMenuBtn');if(btn){btn.setAttribute('aria-expanded','false');btn.innerHTML='<span>☰</span><b>Menu</b>'}}
function toggleMobileMenu(){const open=!body.classList.contains('menu-open');body.classList.toggle('menu-open',open);const btn=$('#mobileMenuBtn');if(btn){btn.setAttribute('aria-expanded',open?'true':'false');btn.innerHTML=open?'<span>×</span><b>Fechar</b>':'<span>☰</span><b>Menu</b>'}}
function isPageAllowed(page){const owner=Boolean(currentProfile?.dono_sistema),plan=low(currentCompany?.plano_codigo||'free');if(page==='developer')return true;if(owner)return true;if(page==='admin')return false;if(page==='appointments')return canAgenda;if(page==='ai')return plan==='business';if(page==='affiliates')return ['profissional','business'].includes(plan);return true}
function applyPlanNavigation(){const owner=Boolean(currentProfile?.dono_sistema),plan=low(currentCompany?.plano_codigo||'free');$$('[data-page="admin"]').forEach(el=>el.classList.toggle('hidden',!owner));$$('[data-page="appointments"]').forEach(el=>el.classList.toggle('hidden',!(owner||canAgenda)));$$('[data-page="ai"]').forEach(el=>el.classList.toggle('hidden',!(owner||plan==='business')));$$('[data-page="affiliates"]').forEach(el=>el.classList.toggle('hidden',!(owner||['profissional','business'].includes(plan))))}
async function refreshCapabilities(){if(!supabase||!currentCompany?.id){canAgenda=false;applyPlanNavigation();return}if(currentProfile?.dono_sistema){canAgenda=true;applyPlanNavigation();return}const {data,error}=await supabase.rpc('pode_gerenciar_agenda_empresa',{p_empresa_id:currentCompany.id});canAgenda=!error&&Boolean(data);if(error)console.error('RENOVA capabilities',error);applyPlanNavigation()}

async function refreshDashboard(){if(supabase&&currentCompany?.id)try{await loadDashboard({supabase,company:currentCompany,profile:currentProfile})}catch(err){console.error('Dashboard refresh',err)}}
async function goToPage(page){if(!pageMeta[page])page='dashboard';if(!isPageAllowed(page)){showToast('Este módulo não está disponível no plano ou perfil atual.');page='dashboard'}$$('.page').forEach(el=>el.classList.toggle('active',el.id===`${page}Page`));$$('[data-page]').forEach(btn=>btn.classList.toggle('active',btn.dataset.page===page));const [eyebrow,title]=pageMeta[page];$('#pageEyebrow').textContent=eyebrow;$('#pageTitle').textContent=title;closeMobileMenu();if(page==='dashboard'){await refreshDashboard();return}if(page==='appointments'){await agendaModule?.load?.();return}if(page==='developer'){developerPage?.render?.();return}await internalModules?.load?.(page);await extrasModules?.enhance?.(page);if(page==='products')await productManagement?.enhance?.(()=>goToPage('products'));if(page==='members')networkingMediaModule?.enhance?.();if(page==='admin')await adminPlanModule?.enhance?.()}
function initials(name='RENOVA'){return name.split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]?.toUpperCase()).join('')||'R'}
function setConnection(status,ok=true){const badge=$('#connectionBadge');if(!badge)return;badge.innerHTML=`<i></i> ${status}`;badge.style.opacity=ok?'1':'.78'}

function renderUserContext(){const profile=currentProfile||{},company=currentCompany||{},name=profile.nome||currentUser?.user_metadata?.name||currentUser?.email?.split('@')[0]||'Usuário RENOVA';const role=profile.dono_sistema?'Conta Dono':(profile.admin?'Administrador':(profile.papel||'Usuário'));$('#sidebarUserName').textContent=name;$('#sidebarUserRole').textContent=role;$('#userAvatar').textContent=initials(name);const welcome=$('#welcomeText');if(welcome)welcome.textContent=`Olá, ${name.split(' ')[0]}! 👋`;const metricCompany=$('#metricCompany');if(metricCompany)metricCompany.textContent=company.nome||'RENOVA';const metricPlan=$('#metricPlan');if(metricPlan)metricPlan.textContent=profile.dono_sistema?'DONO':(company.plano_codigo||'free').toUpperCase();const metricRole=$('#metricRole');if(metricRole)metricRole.textContent=role;const metricStatus=$('#metricStatus');if(metricStatus)metricStatus.textContent='Conectado';applyPlanNavigation()}

async function loadProfileAndCompany(){if(!supabase||!currentUser)return;try{const {data:profile,error:profileError}=await supabase.from('perfis').select('id,nome,email,telefone,papel,admin,dono_sistema,ativo,tema_interface').eq('id',currentUser.id).maybeSingle();if(profileError)throw profileError;currentProfile=profile||{};let company=null;if(currentProfile.dono_sistema){const {data:owned}=await supabase.from('empresas').select('id,nome,plano_codigo,status_assinatura,ativo,owner_user_id,plano_valido_ate,plano_pagamento_confirmado').eq('owner_user_id',currentUser.id).eq('ativo',true).order('created_at',{ascending:true}).limit(1).maybeSingle();company=owned||null;if(!company){const saved=localStorage.getItem('renova_company_id');if(saved){const {data}=await supabase.from('empresas').select('id,nome,plano_codigo,status_assinatura,ativo,owner_user_id,plano_valido_ate,plano_pagamento_confirmado').eq('id',saved).eq('ativo',true).maybeSingle();company=data||null}}}if(!company){const {data:links,error:linkError}=await supabase.from('empresa_usuarios').select('empresa_id,papel,ativo').eq('user_id',currentUser.id).eq('ativo',true).limit(1);if(linkError)throw linkError;const companyId=links?.[0]?.empresa_id;if(companyId){const {data,error}=await supabase.from('empresas').select('id,nome,plano_codigo,status_assinatura,ativo,owner_user_id,plano_valido_ate,plano_pagamento_confirmado').eq('id',companyId).maybeSingle();if(error)throw error;company=data||null}}currentCompany=company||{};if(currentCompany?.id)localStorage.setItem('renova_company_id',currentCompany.id);await refreshCapabilities();renderUserContext()}catch(err){console.error('RENOVA context error',err);showToast('Sessão conectada, mas o contexto da empresa precisa ser validado.');renderUserContext()}}

function resetModules(){internalModules?.reset?.();extrasModules?.reset?.();adminPlanModule?.reset?.();networkingMediaModule?.reset?.();productManagement?.reset?.();agendaModule?.reset?.();publicBooking?.close?.()}
async function showApp(session){currentUser=session.user;publicStore?.hide?.();$('#authView').classList.add('hidden');$('#appView').classList.remove('hidden');setConnection('Conectado');await loadProfileAndCompany();resetModules();if(!currentCompany?.id){showToast('Nenhuma empresa ativa vinculada a esta conta.');return}await goToPage('dashboard')}
function showAuth(){currentUser=null;currentProfile=null;currentCompany=null;canAgenda=false;resetModules();publicStore?.hide?.();$('#appView').classList.add('hidden');$('#authView').classList.remove('hidden')}
async function showPublic(){currentUser=null;currentProfile=null;currentCompany=null;canAgenda=false;resetModules();$('#appView').classList.add('hidden');$('#authView').classList.add('hidden');publicStore?.show?.();if(!publicCatalogLoaded&&publicStore){publicCatalogLoaded=true;try{await publicStore.loadCatalog()}catch(err){publicCatalogLoaded=false;console.error('Public store load',err)}}}
function ensureAuthBackButton(){if($('#backPublicBtn'))return;const forgot=$('#forgotBtn');if(!forgot)return;const btn=document.createElement('button');btn.id='backPublicBtn';btn.className='link-btn';btn.type='button';btn.textContent='← Voltar para a vitrine pública';btn.addEventListener('click',showPublic);forgot.insertAdjacentElement('afterend',btn)}

async function login(event){event.preventDefault();if(!supabase)return showToast('A chave pública do Supabase ainda não foi configurada.');const email=$('#loginEmail').value.trim(),password=$('#loginPassword').value,btn=$('#loginBtn');btn.disabled=true;btn.textContent='Entrando...';try{const {data,error}=await supabase.auth.signInWithPassword({email,password});if(error)throw error;if(!data.session)throw new Error('Sessão não criada.');await showApp(data.session)}catch(err){showToast(err.message||'Não foi possível entrar.')}finally{btn.disabled=false;btn.textContent='Entrar'}}
async function logout(){if(supabase)await supabase.auth.signOut();await showPublic()}
async function forgotPassword(){if(!supabase)return showToast('Conexão pública do Supabase ainda não configurada.');const email=$('#loginEmail').value.trim();if(!email)return showToast('Informe seu e-mail primeiro.');try{const redirectTo=`${location.origin}${location.pathname}`;const {error}=await supabase.auth.resetPasswordForEmail(email,{redirectTo});if(error)throw error;showToast('Enviamos o link de recuperação para seu e-mail.')}catch(err){showToast(err.message||'Não foi possível enviar a recuperação.')}}
function bindUi(){$('#loginForm')?.addEventListener('submit',login);$('#forgotBtn')?.addEventListener('click',forgotPassword);$('#logoutBtn')?.addEventListener('click',logout);$('#themeToggle')?.addEventListener('click',()=>applyTheme(root.dataset.theme==='dark'?'light':'dark'));$('#mobileMenuBtn')?.addEventListener('click',toggleMobileMenu);$('#mobileBackdrop')?.addEventListener('click',closeMobileMenu);$('#mainNav')?.addEventListener('click',e=>{const btn=e.target.closest('[data-page]');if(btn&&!btn.classList.contains('hidden'))goToPage(btn.dataset.page)});$('#developerPageBtn')?.addEventListener('click',()=>goToPage('developer'));document.addEventListener('keydown',e=>{if(e.key==='Escape')closeMobileMenu()});window.addEventListener('resize',()=>{if(innerWidth>760)closeMobileMenu()});ensureAuthBackButton()}

async function initSupabase(){const notice=$('#setupNotice');if(!isSupabaseConfigured()){notice.classList.remove('hidden');notice.innerHTML='<strong>Base Web criada.</strong><br>Falta somente cadastrar a chave pública/publishable do Supabase em <code>js/config.js</code>.';$('#loginBtn').disabled=true;setConnection('Configuração pendente',false);return}supabase=createClient(RENOVA_CONFIG.supabaseUrl,RENOVA_CONFIG.supabasePublishableKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});publicStore=createPublicStore({supabase,config:RENOVA_CONFIG,showToast,onLogin:showAuth,onThemeToggle:()=>applyTheme(root.dataset.theme==='dark'?'light':'dark')});const context=()=>({user:currentUser,profile:currentProfile,company:currentCompany});internalModules=createInternalModules({supabase,getContext:context,showToast,onDataChange:refreshDashboard});extrasModules=createExtrasModules({supabase,getContext:context,showToast});adminPlanModule=createAdminPlanModule({supabase,getContext:context,showToast,onChanged:refreshDashboard});networkingMediaModule=createNetworkingMediaModule();productManagement=createProductManagement({supabase,getContext:context,showToast,onDataChange:refreshDashboard});agendaModule=createAgendaModule({supabase,getContext:context,showToast,onDataChange:refreshDashboard});publicBooking=createPublicBooking({supabase,showToast});developerPage=createDeveloperPage({config:RENOVA_CONFIG,booking:publicBooking});const {data:{session}}=await supabase.auth.getSession();if(session)await showApp(session);else await showPublic();supabase.auth.onAuthStateChange(async(event,session)=>{if(event==='SIGNED_OUT'||!session)await showPublic();else if(event==='SIGNED_IN'||event==='TOKEN_REFRESHED')await showApp(session)})}

applyBrand();applyTheme(preferredTheme());bindUi();initSupabase();
