export function createDeveloperPage({config,booking}){
  function render(){
    const root=document.getElementById('developerPage');if(!root)return;
    const b=config.brand;
    root.innerHTML=`<div class="module-shell"><section class="developer-hero"><article class="developer-hero-copy"><span class="eyebrow">DESENVOLVEDOR • ECOSSISTEMA RENOVA</span><h2>Tecnologia para simplificar a operação e devolver tempo para decisões que realmente importam.</h2><p>O Ecossistema RENOVA foi desenvolvido com uma proposta prática: integrar gestão, vendas, financeiro, relacionamento com clientes, produtos, automações e inteligência em um único ambiente. A ideia é reduzir retrabalho, organizar processos e criar uma base preparada para crescer junto com cada negócio.</p><div class="module-actions" style="margin-top:20px"><button class="module-btn primary" id="developerBookTop" type="button">Agendar consultoria gratuita</button></div></article><aside class="developer-profile-card"><img src="${b.developerPhotoUrl}" alt="${b.developer}"><strong>${b.developer}</strong><span>${b.developerRole}</span><small>Ecossistema RENOVA • Gestão • Controle • Resultados</small></aside></section><section class="developer-grid"><article class="developer-section"><h3>Visão de negócio</h3><p>Antes de pensar em tecnologia, o RENOVA parte da operação real: onde existem gargalos, tarefas repetitivas, perda de informação e dificuldade para acompanhar resultados.</p></article><article class="developer-section"><h3>Automação com propósito</h3><p>Automatizar não é apenas fazer mais rápido. É retirar do caminho o que é repetitivo para que pessoas possam dedicar energia a clientes, estratégia e decisões importantes.</p></article><article class="developer-section"><h3>Arquitetura preparada para evoluir</h3><p>O sistema foi estruturado de forma modular, multiempresa e integrada para permitir evolução contínua sem precisar reconstruir toda a operação a cada novo recurso.</p></article></section><section class="developer-proof"><article><strong>CRM integrado</strong><span>Leads, clientes e oportunidades conectados.</span></article><article><strong>Vendas + Financeiro</strong><span>Uma venda alimenta automaticamente os módulos relacionados.</span></article><article><strong>Produtos e Serviços</strong><span>Catálogo por empresa com gestão própria.</span></article><article><strong>RENOVA IA</strong><span>Inteligência aplicada à rotina e à execução autorizada.</span></article></section><section class="developer-cta"><span class="eyebrow">CONVERSA ESTRATÉGICA</span><h3>Quer analisar seu negócio junto com o desenvolvedor do RENOVA?</h3><p>Agende uma consultoria gratuita. Você escolhe um dos horários realmente disponíveis, informa o contexto e a solicitação entra diretamente no módulo de Agendamentos da Conta Dono.</p><button class="module-btn primary" id="developerBookBottom" type="button">Ver horários da consultoria gratuita</button></section></div>`;
    const open=()=>booking?.openBySlug?.('consultoria-gratuita-desenvolvedor-renova');root.querySelector('#developerBookTop')?.addEventListener('click',open);root.querySelector('#developerBookBottom')?.addEventListener('click',open);
  }
  return{render};
}
