const esc=(v='')=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const money=new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'});
const dt=v=>v?new Intl.DateTimeFormat('pt-BR',{dateStyle:'short',timeStyle:String(v).includes('T')?'short':undefined}).format(new Date(v)):'—';
const low=v=>String(v??'').trim().toLowerCase();
const statusClass=v=>{const s=low(v);if(['ativo','ativa','aprovado','aprovada','pago','paga','pronto'].includes(s))return'ok';if(['pendente','aguardando','processando'].includes(s))return'warn';if(['rejeitado','rejeitada','cancelado','cancelada','erro','inativo'].includes(s))return'bad';return'info'};
const badge=v=>`<span class="module-status ${statusClass(v)}">${esc(v||'—')}</span>`;
const empty=t=>`<div class="module-empty">${esc(t)}</div>`;

export function createExtrasModules({supabase,getContext,showToast}){
  const ctx=()=>getContext?.()||{};
  const isOwner=()=>Boolean(ctx().profile?.dono_sistema);
  const companyId=()=>ctx().company?.id;
  const userId=()=>ctx().user?.id;
  const companyOwner=()=>isOwner()||ctx().company?.owner_user_id===userId();

  function modal(title,html,onReady){document.getElementById('extrasModalBackdrop')?.remove();const wrap=document.createElement('div');wrap.id='extrasModalBackdrop';wrap.className='module-modal-backdrop';wrap.innerHTML=`<div class="module-modal" role="dialog" aria-modal="true"><div class="module-modal-head"><h3>${esc(title)}</h3><button class="module-modal-close" data-extra-close type="button">×</button></div><div class="module-modal-body">${html}</div></div>`;document.body.appendChild(wrap);const close=()=>wrap.remove();wrap.addEventListener('click',e=>{if(e.target===wrap||e.target.closest('[data-extra-close]'))close()});onReady?.(wrap,close);return wrap}

  async function affiliateMaterials(){const page=document.getElementById('affiliatesPage'),shell=page?.querySelector('.module-shell'),empresa=companyId();if(!shell||!empresa||document.getElementById('affiliateMaterialsPanel'))return;const host=document.createElement('article');host.id='affiliateMaterialsPanel';host.className='module-panel';host.innerHTML='<div class="module-loading">Carregando materiais de divulgação...</div>';shell.appendChild(host);const {data,error}=await supabase.from('materiais_afiliados').select('id,titulo,categoria,tipo,arquivo,legenda,texto_whatsapp,ativo,origem,status_geracao,link_afiliado,criado_em').eq('empresa_id',empresa).order('ordem').order('criado_em',{ascending:false}).limit(300);if(error){host.innerHTML=empty(error.message);return}const rows=data||[];host.innerHTML=`<div class="module-panel-head"><div><h3>Materiais para Afiliados</h3><p>Imagens, e-books, copies e textos de WhatsApp disponíveis para divulgação.</p></div>${companyOwner()?'<button class="module-btn primary" id="materialNew" type="button">+ Novo material</button>':''}</div><div class="module-grid" style="padding:14px">${rows.length?rows.map(m=>`<article class="module-card"><div class="module-badge-row">${badge(m.ativo?'Ativo':'Inativo')}${badge(m.status_geracao)}<span class="module-badge">${esc(m.categoria||'Geral')}</span></div><h3>${esc(m.titulo)}</h3><p>${esc(m.legenda||m.texto_whatsapp||'Material RENOVA')}</p><div class="module-card-footer">${m.arquivo?`<a class="module-mini" href="${esc(m.arquivo)}" target="_blank" rel="noopener">Abrir material</a>`:'<span></span>'}${m.texto_whatsapp?`<button class="module-mini" data-copy-material="${m.id}" type="button">Copiar texto</button>`:''}</div></article>`).join(''):empty('Nenhum material publicado.')}</div>`;
    host.querySelectorAll('[data-copy-material]').forEach(btn=>btn.addEventListener('click',async()=>{const item=rows.find(x=>x.id===btn.dataset.copyMaterial);if(!item)return;const text=[item.texto_whatsapp||item.legenda||'',item.link_afiliado||''].filter(Boolean).join('\n\n');try{await navigator.clipboard.writeText(text);showToast('Texto de divulgação copiado.')}catch{showToast('Não foi possível copiar automaticamente.')}}));
    host.querySelector('#materialNew')?.addEventListener('click',()=>modal('Novo material para afiliados',`<form id="materialForm" class="module-form"><label>Título<input id="matTitle" class="module-input" required></label><div class="module-form-grid"><label>Categoria<input id="matCategory" class="module-input" value="Geral"></label><label>Tipo<select id="matType" class="module-select"><option>Imagem</option><option>E-book</option><option>Vídeo</option><option>Texto</option><option>Link</option></select></label></div><label>URL do arquivo ou material<input id="matFile" class="module-input" type="url" placeholder="https://..."></label><label>Legenda<textarea id="matCaption" class="module-textarea"></textarea></label><label>Texto para WhatsApp<textarea id="matWhats" class="module-textarea"></textarea></label><div class="module-form-actions"><button class="module-btn" data-extra-close type="button">Cancelar</button><button class="module-btn primary" type="submit">Publicar material</button></div></form>`,(m,close)=>m.querySelector('#materialForm').addEventListener('submit',async e=>{e.preventDefault();const row={empresa_id:empresa,usuario_id:userId(),titulo:m.querySelector('#matTitle').value.trim(),categoria:m.querySelector('#matCategory').value.trim()||'Geral',tipo:m.querySelector('#matType').value,arquivo:m.querySelector('#matFile').value.trim()||null,legenda:m.querySelector('#matCaption').value.trim()||null,texto_whatsapp:m.querySelector('#matWhats').value.trim()||null,ativo:true,origem:'manual_web',status_geracao:'pronto'};const {error}=await supabase.from('materiais_afiliados').insert(row);if(error)return showToast(error.message);close();showToast('Material publicado para os afiliados.');host.remove();affiliateMaterials()})));
  }

  async function networking(){const page=document.getElementById('membersPage'),shell=page?.querySelector('.module-shell');if(!shell||document.getElementById('networkingPanel'))return;const host=document.createElement('article');host.id='networkingPanel';host.className='module-panel';host.innerHTML='<div class="module-loading">Carregando Networking RENOVA...</div>';shell.appendChild(host);const [{data:posts,error},{data:comments}]=await Promise.all([supabase.from('comunidade_posts').select('id,autor_id,tipo,titulo,conteudo,material_url,status,criado_em,aprovado_em').order('criado_em',{ascending:false}).limit(120),supabase.from('comunidade_comentarios').select('id,post_id,autor_id,conteudo,criado_em').order('criado_em').limit(600)]);if(error){host.innerHTML=empty(error.message);return}const ps=posts||[],cs=comments||[];host.innerHTML=`<div class="module-panel-head"><div><h3>Networking RENOVA</h3><p>Troca de conhecimento entre membros. Publicações passam pelas regras e moderação do Ecossistema.</p></div><button class="module-btn primary" id="networkPostNew" type="button">+ Publicar</button></div><div style="display:grid;gap:12px;padding:14px">${ps.length?ps.map(p=>{const pc=cs.filter(c=>c.post_id===p.id);return `<article class="module-card"><div class="module-badge-row">${badge(p.status)}<span class="module-badge">${esc(p.tipo)}</span></div><h3>${esc(p.titulo)}</h3><p style="white-space:pre-wrap">${esc(p.conteudo)}</p>${p.material_url?`<a class="module-mini" href="${esc(p.material_url)}" target="_blank" rel="noopener">Abrir material</a>`:''}<small style="display:block;margin-top:10px;color:var(--muted)">${dt(p.criado_em)} • ${pc.length} comentário(s)</small>${p.status==='aprovado'?`<div style="display:grid;gap:6px;margin-top:10px">${pc.map(c=>`<div class="module-note">${esc(c.conteudo)}<small style="display:block;margin-top:4px">${dt(c.criado_em)}</small></div>`).join('')}<form data-comment-form="${p.id}" class="module-form" style="grid-template-columns:1fr auto;display:grid"><input class="module-input" name="comment" placeholder="Escreva um comentário..." required><button class="module-btn" type="submit">Comentar</button></form></div>`:''}${isOwner()&&p.status==='pendente'?`<div class="module-row-actions" style="margin-top:10px"><button class="module-mini" data-post-approve="${p.id}" type="button">Aprovar</button><button class="module-mini" data-post-reject="${p.id}" type="button">Rejeitar</button></div>`:''}</article>`}).join(''):empty('Nenhuma publicação disponível.')}</div>`;
    host.querySelector('#networkPostNew')?.addEventListener('click',()=>modal('Nova publicação no Networking RENOVA',`<form id="networkForm" class="module-form"><div class="module-form-grid"><label>Tipo<select id="netType" class="module-select"><option value="ideia">Ideia</option><option value="duvida">Dúvida</option><option value="material">Material</option><option value="resultado">Resultado / aprendizado</option></select></label><label>Título<input id="netTitle" class="module-input" required></label></div><label>Conteúdo<textarea id="netContent" class="module-textarea" required></textarea></label><label>Link de material (opcional)<input id="netUrl" class="module-input" type="url" placeholder="https://..."></label><div class="module-note">A publicação será enviada para aprovação. Conteúdo fora do tema, promessas financeiras, política/religião, linguagem agressiva e divulgação externa indevida podem ser recusados.</div><div class="module-form-actions"><button class="module-btn" data-extra-close type="button">Cancelar</button><button class="module-btn primary" type="submit">Enviar para aprovação</button></div></form>`,(m,close)=>m.querySelector('#networkForm').addEventListener('submit',async e=>{e.preventDefault();const {error}=await supabase.from('comunidade_posts').insert({autor_id:userId(),tipo:m.querySelector('#netType').value,titulo:m.querySelector('#netTitle').value.trim(),conteudo:m.querySelector('#netContent').value.trim(),material_url:m.querySelector('#netUrl').value.trim()||null,status:'pendente'});if(error)return showToast(error.message);close();showToast('Publicação enviada para aprovação.');host.remove();networking()})));
    host.querySelectorAll('[data-comment-form]').forEach(form=>form.addEventListener('submit',async e=>{e.preventDefault();const input=form.elements.comment,text=input.value.trim();if(!text)return;const {error}=await supabase.from('comunidade_comentarios').insert({post_id:form.dataset.commentForm,autor_id:userId(),conteudo:text});if(error)return showToast(error.message);showToast('Comentário publicado.');host.remove();networking()}));
    host.querySelectorAll('[data-post-approve]').forEach(btn=>btn.addEventListener('click',async()=>{const {error}=await supabase.from('comunidade_posts').update({status:'aprovado',aprovado_por:userId(),aprovado_em:new Date().toISOString(),atualizado_em:new Date().toISOString()}).eq('id',btn.dataset.postApprove);if(error)return showToast(error.message);showToast('Publicação aprovada.');host.remove();networking()}));
    host.querySelectorAll('[data-post-reject]').forEach(btn=>btn.addEventListener('click',async()=>{const {error}=await supabase.from('comunidade_posts').update({status:'rejeitado',aprovado_por:userId(),aprovado_em:new Date().toISOString(),atualizado_em:new Date().toISOString()}).eq('id',btn.dataset.postReject);if(error)return showToast(error.message);showToast('Publicação rejeitada.');host.remove();networking()}));
  }

  async function settingsExtras(){const page=document.getElementById('settingsPage'),shell=page?.querySelector('.module-shell'),empresa=companyId();if(!shell||!empresa)return;await Promise.all([vault(shell,empresa),subscriptions(shell,empresa)])}
  async function subscriptions(shell,empresa){if(document.getElementById('subscriptionsPanel'))return;const host=document.createElement('article');host.id='subscriptionsPanel';host.className='module-panel';host.innerHTML='<div class="module-loading">Carregando assinaturas...</div>';shell.appendChild(host);const {data,error}=await supabase.from('assinaturas').select('id,plano_codigo,status,valor,moeda,provider,provider_subscription_id,inicio_em,proxima_cobranca_em,pago_em,cancelada_em,criado_em').eq('empresa_id',empresa).order('criado_em',{ascending:false}).limit(100);if(error){host.innerHTML=empty(error.message);return}const rows=data||[];host.innerHTML=`<div class="module-panel-head"><div><h3>Assinaturas</h3><p>Status e próximas cobranças registradas no RENOVA.</p></div></div><div class="module-table-wrap">${rows.length?`<table class="module-table"><thead><tr><th>Plano</th><th>Valor</th><th>Provedor</th><th>Início</th><th>Próxima cobrança</th><th>Status</th></tr></thead><tbody>${rows.map(a=>`<tr><td><strong>${esc(a.plano_codigo)}</strong></td><td>${money.format(Number(a.valor||0))}</td><td>${esc(a.provider||'—')}</td><td>${dt(a.inicio_em||a.criado_em)}</td><td>${dt(a.proxima_cobranca_em)}</td><td>${badge(a.status)}</td></tr>`).join('')}</tbody></table>`:empty('Nenhuma assinatura registrada para esta empresa.')}</div>`}

  async function vault(shell,empresa){if(document.getElementById('vaultPanel'))return;const host=document.createElement('article');host.id='vaultPanel';host.className='module-panel';host.innerHTML='<div class="module-loading">Abrindo Cofre de Acessos...</div>';shell.appendChild(host);const {data,error}=await supabase.rpc('cofre_listar_acessos',{p_escopo:null,p_empresa_id:null});if(error){host.innerHTML=empty(error.message);return}const rows=data||[];host.innerHTML=`<div class="module-panel-head"><div><h3>Cofre de Acessos</h3><p>Senhas, chaves e tokens ficam cifrados no Vault do Supabase. O segredo só é exibido após uma ação explícita de revelar.</p></div><button class="module-btn primary" id="vaultNew" type="button">+ Novo acesso</button></div><div class="module-table-wrap">${rows.length?`<table class="module-table"><thead><tr><th>Acesso</th><th>Escopo</th><th>Usuário / Login</th><th>URL</th><th>Equipe</th><th>Ações</th></tr></thead><tbody>${rows.map(a=>`<tr><td><strong>${esc(a.titulo)}</strong><small>${esc(a.servico||a.categoria||'Geral')}</small></td><td>${badge(a.escopo)}</td><td>${esc(a.usuario_login||'—')}</td><td>${a.url?`<a href="${esc(a.url)}" target="_blank" rel="noopener">Abrir</a>`:'—'}</td><td>${a.compartilhado_equipe?'Compartilhado':'Privado'}</td><td><div class="module-row-actions">${a.pode_revelar?`<button class="module-mini" data-vault-reveal="${a.id}" type="button">Revelar</button>`:''}${a.pode_editar?`<button class="module-mini" data-vault-delete="${a.id}" type="button">Excluir</button>`:''}</div></td></tr>`).join('')}</tbody></table>`:empty('Nenhum acesso salvo no Cofre.')}</div>`;
    host.querySelector('#vaultNew')?.addEventListener('click',()=>modal('Novo acesso no Cofre RENOVA',`<form id="vaultForm" class="module-form"><div class="module-form-grid"><label>Escopo<select id="vaultScope" class="module-select"><option value="pessoal">Pessoal</option><option value="empresa">Empresa atual</option>${isOwner()?'<option value="sistema">Sistema RENOVA</option>':''}</select></label><label>Título<input id="vaultTitle" class="module-input" required></label></div><div class="module-form-grid"><label>Serviço<input id="vaultService" class="module-input" placeholder="Ex.: Mercado Pago"></label><label>Categoria<input id="vaultCategory" class="module-input" value="Geral"></label></div><label>Usuário / Login<input id="vaultLogin" class="module-input"></label><label>Senha, chave ou token<input id="vaultSecret" class="module-input" type="password" autocomplete="new-password" required></label><label>URL<input id="vaultUrl" class="module-input" type="url" placeholder="https://..."></label><label>Observações<textarea id="vaultNotes" class="module-textarea"></textarea></label><label class="module-check"><input id="vaultShared" type="checkbox"><span>Compartilhar com equipe autorizada (somente escopo Empresa)</span></label><div class="module-form-actions"><button class="module-btn" data-extra-close type="button">Cancelar</button><button class="module-btn primary" type="submit">Salvar no cofre</button></div></form>`,(m,close)=>m.querySelector('#vaultForm').addEventListener('submit',async e=>{e.preventDefault();const scope=m.querySelector('#vaultScope').value;const {error}=await supabase.rpc('cofre_criar_acesso',{p_escopo:scope,p_titulo:m.querySelector('#vaultTitle').value.trim(),p_segredo:m.querySelector('#vaultSecret').value,p_empresa_id:scope==='empresa'?empresa:null,p_servico:m.querySelector('#vaultService').value.trim()||null,p_categoria:m.querySelector('#vaultCategory').value.trim()||'Geral',p_usuario_login:m.querySelector('#vaultLogin').value.trim()||null,p_url:m.querySelector('#vaultUrl').value.trim()||null,p_observacoes:m.querySelector('#vaultNotes').value.trim()||null,p_compartilhado_equipe:scope==='empresa'&&m.querySelector('#vaultShared').checked});if(error)return showToast(error.message);m.querySelector('#vaultSecret').value='';close();showToast('Acesso salvo de forma cifrada.');host.remove();vault(shell,empresa)})));
    host.querySelectorAll('[data-vault-reveal]').forEach(btn=>btn.addEventListener('click',async()=>{btn.disabled=true;btn.textContent='Revelando...';const {data,error}=await supabase.rpc('cofre_revelar_acesso',{p_acesso_id:btn.dataset.vaultReveal});btn.disabled=false;btn.textContent='Revelar';if(error)return showToast(error.message);modal('Segredo revelado',`<div class="module-form"><div class="module-note"><strong>Segredo protegido</strong><br>Não compartilhe esta informação fora do contexto autorizado.</div><label>Senha / chave / token<input id="revealedSecret" class="module-input" readonly value="${esc(data||'')}"></label><div class="module-form-actions"><button class="module-btn" id="copySecret" type="button">Copiar</button><button class="module-btn primary" data-extra-close type="button">Fechar</button></div></div>`,m=>{const field=m.querySelector('#revealedSecret');m.querySelector('#copySecret')?.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(field.value);showToast('Segredo copiado.')}catch{field.select();document.execCommand('copy');showToast('Segredo copiado.')}});setTimeout(()=>{if(document.body.contains(m)){field.value='••••••••';showToast('Segredo ocultado automaticamente.')}},30000)})}));
    host.querySelectorAll('[data-vault-delete]').forEach(btn=>btn.addEventListener('click',async()=>{if(!confirm('Excluir este acesso do Cofre RENOVA?'))return;const {error}=await supabase.rpc('cofre_excluir_acesso',{p_acesso_id:btn.dataset.vaultDelete});if(error)return showToast(error.message);showToast('Acesso excluído do cofre.');host.remove();vault(shell,empresa)}));
  }

  async function enhance(page){try{if(page==='affiliates')await affiliateMaterials();if(page==='members')await networking();if(page==='settings')await settingsExtras()}catch(err){console.error('RENOVA extras',page,err);showToast(err?.message||'Não foi possível carregar um recurso complementar.')}}
  function reset(){document.getElementById('extrasModalBackdrop')?.remove()}
  return{enhance,reset};
}
