const esc=(v='')=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const money=new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'});
const slugify=v=>String(v||'renova-food').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,70)||'renova-food';
const low=v=>String(v??'').trim().toLowerCase();

export function createFoodModule({supabase,getContext,config,showToast,onDataChange}){
  const ctx=()=>getContext?.()||{};
  const companyId=()=>ctx().company?.id;
  const companyName=()=>ctx().company?.nome||'RENOVA Food';
  const publicBase=()=>config.githubPagesUrl||location.origin+location.pathname;

  async function saveConfig(form){
    const empresa=companyId();
    const online=form.querySelector('#foodPayOnline').checked,local=form.querySelector('#foodPayLocal').checked;
    if(!online&&!local)throw new Error('Ative pelo menos uma forma de pagamento: online ou no local.');
    const payload={empresa_id:empresa,slug_publico:slugify(form.querySelector('#foodSlug').value),nome_publico:form.querySelector('#foodName').value.trim()||companyName(),descricao:form.querySelector('#foodDesc').value.trim()||null,aceita_retirada:form.querySelector('#foodPickup').checked,aceita_entrega:form.querySelector('#foodDelivery').checked,taxa_entrega:Number(form.querySelector('#foodFee').value||0),pedido_minimo:Number(form.querySelector('#foodMin').value||0),tempo_min_minutos:Number(form.querySelector('#foodTimeMin').value||20),tempo_max_minutos:Number(form.querySelector('#foodTimeMax').value||50),aberto_manual:form.querySelector('#foodOpen').checked,whatsapp:form.querySelector('#foodWhatsapp').value.trim()||null,observacoes_publicas:form.querySelector('#foodNotes').value.trim()||null,pagamento_online_habilitado:online,pagamento_local_habilitado:local,aceita_pix_online:form.querySelector('#foodOnlinePix').checked,aceita_cartao_online:form.querySelector('#foodOnlineCard').checked,aceita_boleto_online:form.querySelector('#foodOnlineBoleto').checked,aceita_dinheiro_local:form.querySelector('#foodLocalCash').checked,aceita_cartao_local:form.querySelector('#foodLocalCard').checked,aceita_pix_local:form.querySelector('#foodLocalPix').checked,ativo:true,atualizado_em:new Date().toISOString()};
    if(online&&!payload.aceita_pix_online&&!payload.aceita_cartao_online&&!payload.aceita_boleto_online)throw new Error('Selecione ao menos um método de pagamento online.');
    if(local&&!payload.aceita_dinheiro_local&&!payload.aceita_cartao_local&&!payload.aceita_pix_local)throw new Error('Selecione ao menos um método de pagamento no local.');
    const {error}=await supabase.from('food_configuracoes').upsert(payload,{onConflict:'empresa_id'});if(error)throw error;
  }

  async function load(){
    const root=document.getElementById('foodPage'),empresa=companyId();if(!root||!empresa)return;
    root.innerHTML='<div class="module-loading">Carregando RENOVA Food...</div>';
    const [{data:cfg,error:cErr},{data:cats,error:catErr},{data:products,error:pErr},{data:mapped,error:mErr},{data:details,error:dErr},{data:mp}]=await Promise.all([
      supabase.from('food_configuracoes').select('*').eq('empresa_id',empresa).maybeSingle(),
      supabase.from('food_categorias').select('*').eq('empresa_id',empresa).order('ordem').order('nome'),
      supabase.from('catalogo_itens').select('id,nome,descricao,preco,preco_promocional,imagem_url,ativo').eq('empresa_id',empresa).eq('ativo',true).order('nome'),
      supabase.from('food_produtos').select('empresa_id,produto_id,categoria_id,disponivel,destaque,ordem').eq('empresa_id',empresa),
      supabase.from('food_pedido_detalhes').select('pedido_id,tipo_atendimento,status_cozinha,previsao_minutos,criado_em').eq('empresa_id',empresa).order('criado_em',{ascending:false}).limit(100),
      supabase.from('mercado_pago_contas').select('status,live_mode,mp_user_id').eq('empresa_id',empresa).maybeSingle()
    ]);
    const firstErr=cErr||catErr||pErr||mErr||dErr;if(firstErr){root.innerHTML=`<div class="module-empty">${esc(firstErr.message)}</div>`;return}
    const orderIds=(details||[]).map(x=>x.pedido_id);let orders=[];if(orderIds.length){const {data}=await supabase.from('pedidos').select('id,codigo,cliente_nome,cliente_telefone,total,status,status_pagamento,forma_pagamento,gateway_pagamento,criado_em').in('id',orderIds);orders=data||[]}
    const orderMap=new Map(orders.map(x=>[x.id,x])),mapping=new Map((mapped||[]).map(x=>[x.produto_id,x]));
    const slug=cfg?.slug_publico||`${slugify(companyName())}-${empresa.slice(0,6)}`;
    const publicUrl=`${publicBase()}?food=${encodeURIComponent(slug)}`;
    const mpConnected=mp?.status==='conectado';
    const paidCount=orders.filter(o=>low(o.status_pagamento)==='pago').length;
    root.innerHTML=`<div class="module-shell">
      <div class="module-toolbar"><div><span class="eyebrow">SOLUÇÃO VERTICAL</span><h2>RENOVA Food</h2><p>Cardápio, pedidos e pagamentos administrados no mesmo painel central do Ecossistema RENOVA.</p></div><div class="module-actions"><button id="foodCopyLink" class="module-btn" type="button">Copiar página pública</button><a class="module-btn primary" href="${esc(publicUrl)}" target="_blank" rel="noopener">Abrir cardápio</a></div></div>
      <div class="food-status-strip"><span class="module-status ${cfg?.aberto_manual?'ok':'warn'}">${cfg?.aberto_manual?'Loja aberta':'Loja fechada'}</span><span>${(mapped||[]).filter(x=>x.disponivel).length} itens no cardápio</span><span>${(details||[]).filter(x=>!['concluido','cancelado'].includes(x.status_cozinha)).length} pedidos em operação</span><span>${paidCount} pagos</span><span class="module-status ${mpConnected?'ok':'warn'}">Mercado Pago ${mpConnected?'conectado':'não conectado'}</span></div>
      <article class="module-panel"><div class="panel-heading"><div><span class="eyebrow">PÁGINA PÚBLICA</span><h3>Configuração do cardápio</h3></div></div><form id="foodConfigForm" class="module-form"><div class="module-form-grid"><label>Nome público<input id="foodName" class="module-input" value="${esc(cfg?.nome_publico||companyName())}"></label><label>Slug público<input id="foodSlug" class="module-input" value="${esc(slug)}"></label></div><label>Descrição<textarea id="foodDesc" class="module-textarea">${esc(cfg?.descricao||'')}</textarea></label><div class="module-form-grid"><label>WhatsApp<input id="foodWhatsapp" class="module-input" value="${esc(cfg?.whatsapp||'')}"></label><label>Pedido mínimo<input id="foodMin" class="module-input" type="number" min="0" step="0.01" value="${Number(cfg?.pedido_minimo||0)}"></label></div><div class="module-form-grid"><label>Taxa de entrega<input id="foodFee" class="module-input" type="number" min="0" step="0.01" value="${Number(cfg?.taxa_entrega||0)}"></label><label>Tempo mínimo (min)<input id="foodTimeMin" class="module-input" type="number" min="1" value="${Number(cfg?.tempo_min_minutos||20)}"></label></div><label>Tempo máximo (min)<input id="foodTimeMax" class="module-input" type="number" min="1" value="${Number(cfg?.tempo_max_minutos||50)}"></label><div class="module-form-grid"><label class="module-check"><input id="foodPickup" type="checkbox" ${cfg?.aceita_retirada!==false?'checked':''}><span>Aceitar retirada</span></label><label class="module-check"><input id="foodDelivery" type="checkbox" ${cfg?.aceita_entrega?'checked':''}><span>Aceitar entrega</span></label></div><label class="module-check"><input id="foodOpen" type="checkbox" ${cfg?.aberto_manual!==false?'checked':''}><span>Receber pedidos agora</span></label><label>Informações públicas<textarea id="foodNotes" class="module-textarea">${esc(cfg?.observacoes_publicas||'')}</textarea></label>
      <section class="food-payment-config"><div><span class="eyebrow">PAGAMENTOS</span><h3>Como o cliente pode pagar</h3><p>Pagamento online usa a conta Mercado Pago do próprio estabelecimento. O RENOVA não recebe o valor da venda.</p></div><div class="food-payment-config-grid"><div class="food-payment-option"><label class="module-check"><input id="foodPayOnline" type="checkbox" ${cfg?.pagamento_online_habilitado?'checked':''}><span><strong>Pagar agora</strong><small>Checkout transparente Mercado Pago</small></span></label><div class="food-payment-sub"><label class="module-check"><input id="foodOnlinePix" type="checkbox" ${cfg?.aceita_pix_online!==false?'checked':''}><span>PIX</span></label><label class="module-check"><input id="foodOnlineCard" type="checkbox" ${cfg?.aceita_cartao_online!==false?'checked':''}><span>Cartão</span></label><label class="module-check"><input id="foodOnlineBoleto" type="checkbox" ${cfg?.aceita_boleto_online?'checked':''}><span>Boleto</span></label><div class="module-note">${mpConnected?'Mercado Pago conectado e pronto para checkout transparente.':'Conecte o Mercado Pago em Configurações para liberar pagamentos online.'}</div></div></div><div class="food-payment-option"><label class="module-check"><input id="foodPayLocal" type="checkbox" ${cfg?.pagamento_local_habilitado!==false?'checked':''}><span><strong>Pagar no local</strong><small>Pagamento na entrega, retirada ou balcão</small></span></label><div class="food-payment-sub"><label class="module-check"><input id="foodLocalCash" type="checkbox" ${cfg?.aceita_dinheiro_local!==false?'checked':''}><span>Dinheiro</span></label><label class="module-check"><input id="foodLocalPix" type="checkbox" ${cfg?.aceita_pix_local!==false?'checked':''}><span>PIX no local</span></label><label class="module-check"><input id="foodLocalCard" type="checkbox" ${cfg?.aceita_cartao_local!==false?'checked':''}><span>Cartão na maquininha</span></label></div></div></div></section>
      <div class="module-form-actions"><button class="module-btn primary" type="submit">Salvar RENOVA Food</button></div></form></article>
      <div class="food-two-col"><article class="module-panel"><div class="panel-heading"><div><span class="eyebrow">ORGANIZAÇÃO</span><h3>Categorias</h3></div><button id="foodAddCategory" class="module-btn" type="button">+ Categoria</button></div><div class="food-list">${(cats||[]).length?(cats||[]).map(c=>`<div class="food-row"><div><strong>${esc(c.nome)}</strong><small>${esc(c.descricao||'')}</small></div><button class="module-mini" data-food-cat-delete="${c.id}" type="button">Excluir</button></div>`).join(''):'<div class="module-empty">Crie categorias como Lanches, Bebidas, Pizzas ou Sobremesas.</div>'}</div></article><article class="module-panel"><div class="panel-heading"><div><span class="eyebrow">CATÁLOGO</span><h3>Produtos no cardápio</h3></div></div><div class="food-list">${(products||[]).length?(products||[]).map(p=>{const m=mapping.get(p.id);return `<div class="food-row"><div><strong>${esc(p.nome)}</strong><small>${money.format(Number(p.preco_promocional||p.preco||0))}</small></div><div class="food-row-actions"><select class="module-select" data-food-category="${p.id}"><option value="">Sem categoria</option>${(cats||[]).map(c=>`<option value="${c.id}" ${m?.categoria_id===c.id?'selected':''}>${esc(c.nome)}</option>`).join('')}</select><label class="module-check compact"><input data-food-product="${p.id}" type="checkbox" ${m?.disponivel?'checked':''}><span>No cardápio</span></label></div></div>`}).join(''):'<div class="module-empty">Cadastre produtos em Produtos / Serviços primeiro.</div>'}</div></article></div>
      <article class="module-panel"><div class="panel-heading"><div><span class="eyebrow">OPERAÇÃO</span><h3>Pedidos RENOVA Food</h3></div></div><div class="module-table-wrap">${(details||[]).length?`<table class="module-table"><thead><tr><th>Pedido</th><th>Cliente</th><th>Atendimento</th><th>Total</th><th>Pagamento</th><th>Cozinha</th></tr></thead><tbody>${(details||[]).map(d=>{const o=orderMap.get(d.pedido_id)||{},isPaid=low(o.status_pagamento)==='pago',isOnline=low(o.gateway_pagamento)==='mercado_pago'||String(o.forma_pagamento||'').includes('Mercado Pago');return `<tr><td><strong>${esc(o.codigo||d.pedido_id.slice(0,8))}</strong><small>${new Date(d.criado_em).toLocaleString('pt-BR')}</small></td><td>${esc(o.cliente_nome||'Cliente')}</td><td>${esc(d.tipo_atendimento)}</td><td>${money.format(Number(o.total||0))}</td><td><div class="food-payment-cell">${isPaid?'<span class="module-status ok">Pago</span>':`<span class="module-status warn">${esc(o.status_pagamento||'pendente')}</span>`}<small>${esc(o.forma_pagamento||'—')}</small>${!isPaid&&!isOnline?`<button class="module-mini" data-food-mark-paid="${d.pedido_id}" type="button">Marcar recebido</button>`:''}</div></td><td><select class="module-select" data-food-status="${d.pedido_id}">${['recebido','aceito','preparando','pronto','saiu_entrega','concluido','cancelado'].map(s=>`<option value="${s}" ${d.status_cozinha===s?'selected':''}>${s.replace('_',' ')}</option>`).join('')}</select></td></tr>`}).join('')}</tbody></table>`:'<div class="module-empty">Nenhum pedido recebido ainda.</div>'}</div></article>
    </div>`;

    root.querySelector('#foodCopyLink')?.addEventListener('click',async()=>{await navigator.clipboard.writeText(publicUrl);showToast('Link do cardápio copiado.')});
    root.querySelector('#foodConfigForm')?.addEventListener('submit',async e=>{e.preventDefault();try{await saveConfig(e.currentTarget);showToast('RENOVA Food atualizado.');await load()}catch(err){showToast(err.message||'Não foi possível salvar.')}});
    root.querySelector('#foodAddCategory')?.addEventListener('click',async()=>{const nome=prompt('Nome da categoria:');if(!nome?.trim())return;const {error}=await supabase.from('food_categorias').insert({empresa_id:empresa,nome:nome.trim(),ordem:(cats||[]).length});if(error)return showToast(error.message);showToast('Categoria criada.');load()});
    root.querySelectorAll('[data-food-cat-delete]').forEach(btn=>btn.addEventListener('click',async()=>{if(!confirm('Excluir esta categoria? Os produtos ficarão sem categoria.'))return;const {error}=await supabase.from('food_categorias').delete().eq('id',btn.dataset.foodCatDelete).eq('empresa_id',empresa);if(error)return showToast(error.message);load()}));
    root.querySelectorAll('[data-food-product]').forEach(input=>input.addEventListener('change',async()=>{const id=input.dataset.foodProduct,cat=root.querySelector(`[data-food-category="${id}"]`)?.value||null;if(input.checked){const {error}=await supabase.from('food_produtos').upsert({empresa_id:empresa,produto_id:id,categoria_id:cat,disponivel:true,atualizado_em:new Date().toISOString()},{onConflict:'empresa_id,produto_id'});if(error){input.checked=false;return showToast(error.message)}}else{const {error}=await supabase.from('food_produtos').delete().eq('empresa_id',empresa).eq('produto_id',id);if(error){input.checked=true;return showToast(error.message)}}showToast('Cardápio atualizado.');await onDataChange?.()}));
    root.querySelectorAll('[data-food-category]').forEach(select=>select.addEventListener('change',async()=>{const id=select.dataset.foodCategory,m=mapping.get(id);if(!m)return;const {error}=await supabase.from('food_produtos').update({categoria_id:select.value||null,atualizado_em:new Date().toISOString()}).eq('empresa_id',empresa).eq('produto_id',id);if(error)showToast(error.message)}));
    root.querySelectorAll('[data-food-mark-paid]').forEach(btn=>btn.addEventListener('click',async()=>{if(!confirm('Confirmar que este pedido foi pago no local? Isso registrará a venda e a receita no painel central.'))return;btn.disabled=true;const {error}=await supabase.from('pedidos').update({status_pagamento:'pago',status:'confirmado',atualizado_em:new Date().toISOString()}).eq('id',btn.dataset.foodMarkPaid).eq('empresa_id',empresa);if(error){btn.disabled=false;return showToast(error.message)}showToast('Pagamento confirmado. Venda e Financeiro atualizados.');await onDataChange?.();await load()}));
    root.querySelectorAll('[data-food-status]').forEach(select=>select.addEventListener('change',async()=>{const {error}=await supabase.from('food_pedido_detalhes').update({status_cozinha:select.value,atualizado_em:new Date().toISOString()}).eq('pedido_id',select.dataset.foodStatus).eq('empresa_id',empresa);if(error)return showToast(error.message);if(select.value==='concluido')await supabase.from('pedidos').update({status:'concluido',atualizado_em:new Date().toISOString()}).eq('id',select.dataset.foodStatus).eq('empresa_id',empresa);if(select.value==='cancelado')await supabase.from('pedidos').update({status:'cancelado',atualizado_em:new Date().toISOString()}).eq('id',select.dataset.foodStatus).eq('empresa_id',empresa);showToast('Status do pedido atualizado.');await onDataChange?.()}));
  }
  return{load,reset(){}};
}
